
name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:
 
    runs-on: ubuntu-latest

 
    steps:

      - uses: actions/checkout@v2

      
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a one-line script
        uses: @cumulusds@v0.0.0
        with:
          file: specs.yml
          credentials: env.SOME_CREDENTIALS
          run: echo credentials 
