
name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  env: 
    ENVIRONMENT: ${file(../specs.json)}
  build:
 
    runs-on: ubuntu-latest
    steps:
    
      - name: Run a one-line script
        run: echo "${ENVIRONMENT}"


