
name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  env: 
    ASBABA: ${file(../specs.json)}
  build:
 
    steps:
      - name: Run a one-line script
        run: echo "${ASBABA}"


