
name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  env: 
    ASBABA: ${file(../specs.json)}

  build:
 
    runs-on: ubuntu-latest

 
    steps:

      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: echo "${ASBABA}"


